homepage:
    pattern:  /
    defaults: { _controller: JoaoAlbuquerqueNewsGroupBundle:NewsGroupUser:new }

joao_albuquerque_news_group_user:
    resource: "@JoaoAlbuquerqueNewsGroupBundle/Controller/NewsGroupUserController.php"
    type:     annotation